image: node:16-alpine

cache:
  paths:
    - node_modules/

stages:
  - test

Test:
  stage: test
  tags:
    - docker
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run test

